### ISSUE TITLE
How to extend the MultiTenant sample for more roles

### ISSUE THREAD

**Issue by jakub-bochenski** [mrochon/b2csamples#35]
Hello and thanks for the useful samples. Also apologies for using this as Q&A but I see no other way to contact you.

Can you suggest how to extend the MultiTenant sample to accommodate more user roles? 
Now it supports either an owner or regular member. What if I wanted to have owners and read-only and read-write members?

My problem is I'm not sure where to store this information. For owner vs. regular member you reuse the group ownership, but where would you record if the user is read-only or read-write in a given tenant?

**Comment by mrochon** [comment]
Thanks for your comments. Sorry I am answering only now (vacation). I do not have a solution to this problem. The issue is that you need user roles need to be per tenant (security group) but there is no Graph entity that has these three keys: user id, group id and role id. I cannot re-use appRoles since in this sample the same user may have different roles in different tenants.

**Comment by mrochon** [comment]
I take it back (a bit). If you disallow the same user being associated (as owner or member) of more than one tenant then you can use the standard Graph appRoles to support multiple roles. The sample does it already using the same approach as described in the [AppRoles ](https://github.com/mrochon/b2csamples/tree/master/Policies/AppRoles) sample. You would need to use PowerShell or the AAD portal to define app roles, assign users to them (you can not use groups though since they are already used for tenants). This sample's API already supports [retrieving the roles](https://github.com/mrochon/b2csamples/blob/master/Policies/MultiTenant/source/API/RESTFunctions/Controllers/Tenant.X509.cs#L297) and reporting them to the UI.

**Comment by jakub-bochenski** [comment]
I need to support users to have access to multiple tenants. 

What if I used an extension attribute on user to store this data? It seems brittle but doable (you have to parse it manually etc)

**Comment by jakub-bochenski** [comment]
I can see that, but it's the best I came up with... that or proper [multitenancy](https://docs.microsoft.com/en-us/azure/dotnet-develop-multitenant-applications)

**Comment by mrochon** [comment]
Yes, if every tenant has an AAD of their own then obviously AAD multi-tenancy is the way to go, whether or not you want to support app roles. My sample is about support for supporting users without AAD (and those with AAD) - note that the purpose of the sample is 'support for SaaS apps for small companies'. If I were to extend it to support appRoles and allow multiple tenants per user, I would look to using an external data store (SQL, CosmosDB) so that I can use the composite and simple keys for every role instance (tenant, app, user -> role). Fancy group names will not solve the problem: you cannot pack 3 guids into a group key. Say a user is deleted: how will you delete all their roles, in all tenants?

**Comment by jakub-bochenski** [comment]
The application I have in mind has several thousand users so I wouldn't say it's very large. 

> Fancy group names will not solve the problem: you cannot pack 3 guids into a group key. Say a user is deleted: how will you delete all their roles, in all tenants?

I was thinking about embedding the tenant and role name into the group key. This is for a single application for now. 
That way removing the user is just about removing it from all the groups he's member of

Maybe external DB is the way to go but I was hoping to avoid adding yet another component to this

**Comment by mrochon** [comment]
Yes, if it is just a single application then perhaps fancy group naming may work. You could perhaps consider using different group types (security, distribution, etc.) for tenants and role assignments.
Number of users is not relevant: B2C can hold millions and this sample does not restrict it. It's small tenants, i.e. companies with dozen or so employees who typically do not have their own identity infrastructure. As it happens the sample can also support those with an identity infrastructure as well, particularly those with AAD but that's just an added feature.
